### ISSUE TITLE
ls: cannot access 'usr/bin': No such file or directory

### ISSUE THREAD

**Issue by plutext** [helixarch/debtap#37]
On manjaro, I get

```
==> Generating PKGBUILD file...
ls: cannot access 'usr/bin': No such file or directory
```

even if I create that structure in the current dir.  And /usr/bin does exist.

Any ideas?

**Comment by plutext** [comment]
distro is working fine and ls /usr/bin works from bash prompt.  

In the end I just used makepkg on the generated PKGBUILD thank you.

**Comment by s97712** [comment]
`usr/bin` or `/usr/bin` ?

**Comment by gardotd426** [comment]
@helixarch please don't randomly dismiss people with "your install is broken."

OP of this issue is right, your script is broken.

```
==> Generating PKGBUILD file...
ls: cannot access 'usr/bin': No such file or directory
Error: Cannot create PKGBUILD directory, permission denied. Removing leftover files and exiting...
```

It's not trying to access `/usr/bin`, it's trying to access `usr/bin` WITHIN the package, when there is none (the package trying to be converted doesn't contain a `usr/bin`). 

If you run debtap on a .deb package that DOES contain `usr/bin` files, then it doesn't give this error. This is NOT a "broken installation," your script is broken. 

I'll post a new issue, since you've closed this one.
