### ISSUE TITLE
Changing Output .tar.xz files' permissions from 644 to 755?

### ISSUE THREAD

**Issue by koesherbacon** [helixarch/debtap#9]
I love your app, and I can't tell you how many times I've used it with great success.  I'd like to know if there's a way to change the output .tar.xz files' permissions from 644 to 755?  

I might be new to linux, but since there's a big-ol-lock emblem on the file, I think that means that I won't be able to actually install it unless I manually change it's permissions to 755.

Thanks!

**Comment by helixarch** [comment]
Thank you for finding my app useful. Indeed converted package has 644 permissions, but that's no problem since you are installing it with root privileges anyway. The last program involved in the creation of the converted package is xz, so it is responsible for these permissions. The package's contents permissions may vary, but are identical to those of the original .deb package. In any case that shouldn't bother you, I never had a problem on installing packages converted by debtap.
